# Generated by Django 2.1.7 on 2019-02-12 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Tytuł porady')),
                ('text', models.TextField(verbose_name='Tekst porady')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('test_points', models.SmallIntegerField(verbose_name='Ilość pkt za test')),
                ('likes', models.ManyToManyField(related_name='users_likes', to=settings.AUTH_USER_MODEL)),
                ('passed_by', models.ManyToManyField(related_name='users_tests_passed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive_safe.Advice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nazwa tagu')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Treść pytania')),
                ('answer_a', models.TextField(verbose_name='Odpowiedź A')),
                ('answer_b', models.TextField(verbose_name='Odpowiedź B')),
                ('answer_c', models.TextField(verbose_name='Odpowiedź C')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='Poprawna odpowiedź')),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive_safe.Advice')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='forumanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive_safe.ForumQuestion'),
        ),
        migrations.AddField(
            model_name='forumanswers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advice',
            name='tags',
            field=models.ManyToManyField(to='drive_safe.Tags', verbose_name='Tagi'),
        ),
    ]
